# Usar imagen de SDK para la fase de construcción
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar el archivo .csproj y restaurar dependencias
COPY appGestionBanco.csproj ./
RUN dotnet restore

# Copiar el resto del contenido del proyecto
COPY . ./
RUN dotnet publish -c Release -o out

# Usar la imagen de runtime de .NET para la ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out ./

# Configuración del entorno
ENV APP_NET_CORE appGestionBanco.dll
ENV ASPNETCORE_URLS=http://*:$PORT

# Ejecutar la aplicación
CMD ["dotnet", "appGestionBanco.dll"]
